CREATE DEFINER=`{UserName}`@`%` PROCEDURE `GetSiteTypeList`()
LANGUAGE SQL
NOT DETERMINISTIC
CONTAINS SQL
SQL SECURITY DEFINER
COMMENT ''
BEGIN
    SELECT ID, Description
    FROM SiteType
    ORDER BY ID;
END