CREATE DEFINER=`{UserName}`@`%` PROCEDURE `GetSensitivityList`()
LANGUAGE SQL
NOT DETERMINISTIC
CONTAINS SQL
SQL SECURITY DEFINER
COMMENT ''
BEGIN
	SELECT ID, Description
	FROM Sensitivity ORDER BY ID;
END