CREATE DEFINER=`{UserName}`@`%` PROCEDURE `GetSheetList`()
LANGUAGE SQL
NOT DETERMINISTIC
CONTAINS SQL
SQL SECURITY DEFINER
COMMENT ''
BEGIN
	SELECT Sheet
	FROM (SELECT DISTINCT Sheet FROM Mine ORDER BY Sheet) AS unique_sheets;
END